include $(M)/config.mk

obj-m := xen-platform-pci.o

EXTRA_CFLAGS += -I$(M)/xen-platform-pci

xen-platform-pci-objs := evtchn.o platform-pci.o gnttab.o xen_support.o
xen-platform-pci-objs += features.o platform-compat.o
xen-platform-pci-objs += reboot.o machine_reboot.o
xen-platform-pci-objs += panic-handler.o
xen-platform-pci-objs += platform-pci-unplug.o

xen-platform-pci-objs += xenbus_comms.o
xen-platform-pci-objs += xenbus_xs.o
xen-platform-pci-objs += xenbus_probe.o 
xen-platform-pci-objs += xenbus_dev.o 
xen-platform-pci-objs += xenbus_client.o 
xen-platform-pci-objs += xen_proc.o

# Can we do better ?
ifeq ($(ARCH),ia64)
  xen-platform-pci-objs += xencomm.o xencomm_arch.o xcom_hcall.o xcom_asm.o
endif
